[2024-02-01 15:30:37,528] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_15.dim_case scheduled__2024-01-31T15:30:21.392570+00:00 [queued]>
[2024-02-01 15:30:37,544] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_15.dim_case scheduled__2024-01-31T15:30:21.392570+00:00 [queued]>
[2024-02-01 15:30:37,544] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:30:37,544] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 15:30:37,545] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:30:37,568] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_case> on 2024-01-31 15:30:21.392570+00:00
[2024-02-01 15:30:37,578] {standard_task_runner.py:52} INFO - Started process 5098 to run task
[2024-02-01 15:30:37,582] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_15', 'dim_case', 'scheduled__2024-01-31T15:30:21.392570+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp9xzv68q4', '--error-file', '/tmp/tmp0ivogdhh']
[2024-02-01 15:30:37,583] {standard_task_runner.py:80} INFO - Job 205: Subtask dim_case
[2024-02-01 15:30:37,852] {task_command.py:369} INFO - Running <TaskInstance: project_6_15.dim_case scheduled__2024-01-31T15:30:21.392570+00:00 [running]> on host 1fafaef2f352
[2024-02-01 15:30:38,193] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_15
AIRFLOW_CTX_TASK_ID=dim_case
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:30:21.392570+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-31T15:30:21.392570+00:00
[2024-02-01 15:30:38,317] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 15:30:38,432] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
), parameters: None
[2024-02-01 15:30:38,444] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-01 15:30:38,605] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_15, task_id=dim_case, execution_date=20240131T153021, start_date=20240201T153037, end_date=20240201T153038
[2024-02-01 15:30:38,745] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 15:30:39,042] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
