[2024-02-01 13:41:01,203] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_11.dim_case manual__2024-02-01T13:40:54.240442+00:00 [queued]>
[2024-02-01 13:41:01,237] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_11.dim_case manual__2024-02-01T13:40:54.240442+00:00 [queued]>
[2024-02-01 13:41:01,238] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:41:01,238] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 13:41:01,238] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:41:01,266] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_case> on 2024-02-01 13:40:54.240442+00:00
[2024-02-01 13:41:01,277] {standard_task_runner.py:52} INFO - Started process 1310 to run task
[2024-02-01 13:41:01,283] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_11', 'dim_case', 'manual__2024-02-01T13:40:54.240442+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpfe1zy014', '--error-file', '/tmp/tmpykhjj9_l']
[2024-02-01 13:41:01,284] {standard_task_runner.py:80} INFO - Job 147: Subtask dim_case
[2024-02-01 13:41:01,527] {task_command.py:369} INFO - Running <TaskInstance: project_6_11.dim_case manual__2024-02-01T13:40:54.240442+00:00 [running]> on host 1fafaef2f352
[2024-02-01 13:41:01,907] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_11
AIRFLOW_CTX_TASK_ID=dim_case
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T13:40:54.240442+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T13:40:54.240442+00:00
[2024-02-01 13:41:01,979] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 13:41:02,024] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
), parameters: None
[2024-02-01 13:41:02,032] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-01 13:41:02,117] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_11, task_id=dim_case, execution_date=20240201T134054, start_date=20240201T134101, end_date=20240201T134102
[2024-02-01 13:41:02,180] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 13:41:02,350] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
