[2024-02-01 15:20:04,803] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_13.dim_case scheduled__2024-01-31T15:19:38.505849+00:00 [queued]>
[2024-02-01 15:20:04,820] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_13.dim_case scheduled__2024-01-31T15:19:38.505849+00:00 [queued]>
[2024-02-01 15:20:04,820] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:20:04,820] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 15:20:04,820] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:20:04,848] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_case> on 2024-01-31 15:19:38.505849+00:00
[2024-02-01 15:20:04,856] {standard_task_runner.py:52} INFO - Started process 4609 to run task
[2024-02-01 15:20:04,859] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_13', 'dim_case', 'scheduled__2024-01-31T15:19:38.505849+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpbr_fpy22', '--error-file', '/tmp/tmpck8c8qvv']
[2024-02-01 15:20:04,860] {standard_task_runner.py:80} INFO - Job 166: Subtask dim_case
[2024-02-01 15:20:05,063] {task_command.py:369} INFO - Running <TaskInstance: project_6_13.dim_case scheduled__2024-01-31T15:19:38.505849+00:00 [running]> on host 1fafaef2f352
[2024-02-01 15:20:05,347] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_13
AIRFLOW_CTX_TASK_ID=dim_case
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:19:38.505849+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-31T15:19:38.505849+00:00
[2024-02-01 15:20:05,409] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 15:20:05,470] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
), parameters: None
[2024-02-01 15:20:05,477] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-01 15:20:05,541] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_13, task_id=dim_case, execution_date=20240131T151938, start_date=20240201T152004, end_date=20240201T152005
[2024-02-01 15:20:05,597] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 15:20:05,756] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
