[2024-02-01 15:31:40,512] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_15.dim_prov manual__2024-02-01T15:30:33.313431+00:00 [queued]>
[2024-02-01 15:31:40,530] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_15.dim_prov manual__2024-02-01T15:30:33.313431+00:00 [queued]>
[2024-02-01 15:31:40,530] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:31:40,530] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2024-02-01 15:31:40,530] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:31:40,557] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_prov> on 2024-02-01 15:30:33.313431+00:00
[2024-02-01 15:31:40,565] {standard_task_runner.py:52} INFO - Started process 5173 to run task
[2024-02-01 15:31:40,569] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_15', 'dim_prov', 'manual__2024-02-01T15:30:33.313431+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpmw_s32fx', '--error-file', '/tmp/tmp18qsl29a']
[2024-02-01 15:31:40,569] {standard_task_runner.py:80} INFO - Job 219: Subtask dim_prov
[2024-02-01 15:31:40,791] {task_command.py:369} INFO - Running <TaskInstance: project_6_15.dim_prov manual__2024-02-01T15:30:33.313431+00:00 [running]> on host 1fafaef2f352
[2024-02-01 15:31:41,059] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_15
AIRFLOW_CTX_TASK_ID=dim_prov
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T15:30:33.313431+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T15:30:33.313431+00:00
[2024-02-01 15:31:41,120] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 15:31:41,153] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS province_table (
    province_id INTEGER PRIMARY KEY,
    province_name VARCHAR(255) NOT NULL
);, parameters: None
[2024-02-01 15:31:41,159] {postgres.py:94} INFO - NOTICE:  relation "province_table" already exists, skipping

[2024-02-01 15:31:41,223] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_15, task_id=dim_prov, execution_date=20240201T153033, start_date=20240201T153140, end_date=20240201T153141
[2024-02-01 15:31:41,266] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 15:31:41,488] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
