[2024-02-01 15:30:40,246] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_15.dim_case manual__2024-02-01T15:30:33.313431+00:00 [queued]>
[2024-02-01 15:30:40,270] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_15.dim_case manual__2024-02-01T15:30:33.313431+00:00 [queued]>
[2024-02-01 15:30:40,271] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:30:40,271] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 15:30:40,272] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:30:40,301] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_case> on 2024-02-01 15:30:33.313431+00:00
[2024-02-01 15:30:40,312] {standard_task_runner.py:52} INFO - Started process 5110 to run task
[2024-02-01 15:30:40,316] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_15', 'dim_case', 'manual__2024-02-01T15:30:33.313431+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpe_wu6t1o', '--error-file', '/tmp/tmpzyvgovi3']
[2024-02-01 15:30:40,317] {standard_task_runner.py:80} INFO - Job 208: Subtask dim_case
[2024-02-01 15:30:40,548] {task_command.py:369} INFO - Running <TaskInstance: project_6_15.dim_case manual__2024-02-01T15:30:33.313431+00:00 [running]> on host 1fafaef2f352
[2024-02-01 15:30:40,879] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_15
AIRFLOW_CTX_TASK_ID=dim_case
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T15:30:33.313431+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T15:30:33.313431+00:00
[2024-02-01 15:30:40,958] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 15:30:41,033] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
), parameters: None
[2024-02-01 15:30:41,047] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-01 15:30:41,139] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_15, task_id=dim_case, execution_date=20240201T153033, start_date=20240201T153040, end_date=20240201T153041
[2024-02-01 15:30:41,178] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 15:30:41,379] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
