[2024-01-31 15:49:16,841] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_10.dim_prov manual__2024-01-31T15:49:07.986872+00:00 [queued]>
[2024-01-31 15:49:16,858] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_10.dim_prov manual__2024-01-31T15:49:07.986872+00:00 [queued]>
[2024-01-31 15:49:16,858] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:49:16,858] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 15:49:16,858] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:49:16,894] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_prov> on 2024-01-31 15:49:07.986872+00:00
[2024-01-31 15:49:16,907] {standard_task_runner.py:52} INFO - Started process 8322 to run task
[2024-01-31 15:49:16,913] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_10', 'dim_prov', 'manual__2024-01-31T15:49:07.986872+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmphxera2kc', '--error-file', '/tmp/tmp6fmrhxvw']
[2024-01-31 15:49:16,915] {standard_task_runner.py:80} INFO - Job 127: Subtask dim_prov
[2024-01-31 15:49:17,178] {task_command.py:369} INFO - Running <TaskInstance: project_6_10.dim_prov manual__2024-01-31T15:49:07.986872+00:00 [running]> on host 8ebb6ccf62d7
[2024-01-31 15:49:17,601] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_10
AIRFLOW_CTX_TASK_ID=dim_prov
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:49:07.986872+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T15:49:07.986872+00:00
[2024-01-31 15:49:17,696] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-01-31 15:49:17,780] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS province_table (
    province_id SERIAL PRIMARY KEY,
    province_name VARCHAR(255) NOT NULL
);, parameters: None
[2024-01-31 15:49:17,790] {postgres.py:94} INFO - NOTICE:  relation "province_table" already exists, skipping

[2024-01-31 15:49:17,879] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_10, task_id=dim_prov, execution_date=20240131T154907, start_date=20240131T154916, end_date=20240131T154917
[2024-01-31 15:49:17,935] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 15:49:18,085] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
