[2024-02-01 15:21:12,703] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_13.dim_case manual__2024-02-01T15:19:47.875741+00:00 [queued]>
[2024-02-01 15:21:12,716] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_13.dim_case manual__2024-02-01T15:19:47.875741+00:00 [queued]>
[2024-02-01 15:21:12,717] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:21:12,717] {taskinstance.py:1357} INFO - Starting attempt 3 of 4
[2024-02-01 15:21:12,717] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 15:21:12,743] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_case> on 2024-02-01 15:19:47.875741+00:00
[2024-02-01 15:21:12,755] {standard_task_runner.py:52} INFO - Started process 4696 to run task
[2024-02-01 15:21:12,760] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_13', 'dim_case', 'manual__2024-02-01T15:19:47.875741+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpkuqw8u4y', '--error-file', '/tmp/tmpxuxmvans']
[2024-02-01 15:21:12,761] {standard_task_runner.py:80} INFO - Job 176: Subtask dim_case
[2024-02-01 15:21:13,002] {task_command.py:369} INFO - Running <TaskInstance: project_6_13.dim_case manual__2024-02-01T15:19:47.875741+00:00 [running]> on host 1fafaef2f352
[2024-02-01 15:21:13,300] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_13
AIRFLOW_CTX_TASK_ID=dim_case
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T15:19:47.875741+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T15:19:47.875741+00:00
[2024-02-01 15:21:13,374] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 15:21:13,413] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
), parameters: None
[2024-02-01 15:21:13,419] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-01 15:21:13,483] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_13, task_id=dim_case, execution_date=20240201T151947, start_date=20240201T152112, end_date=20240201T152113
[2024-02-01 15:21:13,539] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 15:21:13,776] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
